import re

# Read the file
with open(r'D:\source_extracted\index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# French translations for all issue names by category
translations = {
    'infrastructure': [
        ('Potholes & road maintenance', 'Nids-de-poule et entretien des routes'),
        ('Public transit (buses, subways, LRT)', 'Transport en commun (autobus, metro, train leger)'),
        ('Traffic signals & signage', 'Feux de circulation et signalisation'),
        ('Sidewalks & pedestrian safety', 'Trottoirs et securite pietonne'),
        ('Bike lanes & cycling infrastructure', 'Pistes cyclables et infrastructures cyclables'),
        ('Snow removal', 'Denigement'),
        ('Street lighting', 'Eclairage des rues'),
        ('Parking enforcement', 'Application des regles de stationnement'),
    ],
    'healthcare': [
        ('Hospital services', 'Services hospitaliers'),
        ('Family doctor access', 'Acces a un medecin de famille'),
        ('Wait times for procedures', 'Temps d\'attente pour les interventions'),
        ('Mental health services', 'Services de sante mentale'),
        ('Pharmacare/prescription coverage', 'Assurance medicaments et couverture des ordonnances'),
        ('Long-term care homes', 'Etablissements de soins de longue duree'),
        ('Medical licensing complaints', 'Plaintes concernant le permis medical'),
        ('Ambulance services', 'Services d\'ambulance'),
    ],
    'education': [
        ('K-12 schools', 'Ecoles primaires et secondaires'),
        ('Post-secondary funding', 'Financement des etudes postsecondaires'),
        ('Special education', 'Education specialisee'),
        ('School bus transportation', 'Transport scolaire'),
        ('Curriculum concerns', 'Preoccupations concernant le programme'),
        ('Teacher certification', 'Certification des enseignants'),
        ('School closures/consolidations', 'Fermetures et consolidations d\'ecoles'),
        ('Indigenous education', 'Education autochtone'),
    ],
    'housing': [
        ('Tenant rights/landlord disputes', 'Droits des locataires et conflits avec le proprietaire'),
        ('Affordable housing programs', 'Programmes de logement abordable'),
        ('Property taxes', 'Impots fonciers'),
        ('Zoning & development permits', 'Zonage et permis d\'amenagement'),
        ('Homelessness services', 'Services pour les sans-abri'),
        ('Rent control', 'Controle des loyers'),
        ('Building permits & inspections', 'Permis de construction et inspections'),
        ('Short-term rentals (Airbnb)', 'Locations a court terme (Airbnb)'),
    ],
    'environment': [
        ('Air quality', 'Qualite de l\'air'),
        ('Water quality (drinking)', 'Qualite de l\'eau potable'),
        ('Waste management & recycling', 'Gestion des dechets et recyclage'),
        ('Contaminated sites', 'Sites contamines'),
        ('Climate change policy', 'Politique sur les changements climatiques'),
        ('Parks & conservation areas', 'Parcs et aires de conservation'),
        ('Wildlife protection', 'Protection de la faune'),
        ('Environmental assessments', 'Evaluations environnementales'),
    ],
    'safety': [
        ('Police complaints', 'Plaintes contre la police'),
        ('Court services', 'Services des tribunaux'),
        ('Correctional facilities', 'Etablissements penitentiaires'),
        ('Fire services', 'Services d\'incendie'),
        ('Emergency management', 'Gestion des urgences'),
        ('Victim services', 'Services aux victimes'),
        ('Legal aid', 'Aide juridique'),
        ('Bylaw enforcement', 'Application des reglements municipaux'),
    ],
    'employment': [
        ('Employment standards (wages, hours)', 'Normes du travail (salaire, horaires)'),
        ('Employment insurance (EI)', 'Assurance-emploi'),
        ('Workplace safety (WSIB/WCB)', 'Securite au travail (CSPAAT/CTT)'),
        ('Labour relations/unions', 'Relations de travail et syndicats'),
        ('Workplace harassment', 'Harcèlement au travail'),
        ('Parental leave', 'Conge parental'),
        ('Foreign worker programs', 'Programmes pour travailleurs etrangers'),
        ('Apprenticeships & trades', 'Apprentissages et metiers'),
    ],
    'social': [
        ('Social assistance (welfare)', 'Aide sociale'),
        ('Child benefits', 'Allocations pour enfants'),
        ('Disability benefits', 'Prestations pour personnes handicapees'),
        ('Seniors benefits (OAS/GIS)', 'Prestations pour aines (SV/SRG)'),
        ('Child protection (CAS)', 'Protection de l\'enfance (SPE)'),
        ('Food banks & community services', 'Banques alimentaires et services communautaires'),
        ('Housing subsidies', 'Subventions au logement'),
        ('Newcomer settlement services', 'Services d\'etablissement pour nouveaux arrivants'),
    ],
    'taxes': [
        ('Income tax', 'Impot sur le revenu'),
        ('Property tax assessment', 'Evaluation fonciere'),
        ('Sales tax (GST/HST/PST)', 'Taxe de vente (TPS/TVH/TVQ)'),
        ('Corporate tax', 'Impot des societes'),
        ('Tax disputes & appeals', 'Differends fiscaux et appels'),
        ('Carbon tax/rebate', 'Taxe sur le carbone et remboursement'),
        ('Tax credits for individuals', 'Credits d\'impot pour particuliers'),
        ('Financial consumer protection', 'Protection des consommateurs financiers'),
    ],
    'immigration': [
        ('Permanent residence applications', 'Demandes de residence permanente'),
        ('Work permits', 'Permis de travail'),
        ('Study permits', 'Permis d\'etudes'),
        ('Family sponsorship', 'Parrainage familial'),
        ('Refugee claims', 'Demandes d\'asile'),
        ('Citizenship applications', 'Demandes de citoyennete'),
        ('Visitor visas', 'Visas de visiteur'),
        ('Immigration detention', 'Detention en matiere d\'immigration'),
    ],
    'consumer': [
        ('Consumer complaints', 'Plaintes des consommateurs'),
        ('Privacy complaints', 'Plaintes en matiere de vie privee'),
        ('Internet/telecom complaints', 'Plaintes concernant Internet et les telecommunications'),
        ('Banking complaints', 'Plaintes bancaires'),
        ('Product safety', 'Securite des produits'),
        ('False advertising', 'Publicite mensongere'),
        ('Warranty issues', 'Problemes de garantie'),
        ('Data breaches', 'Violations de donnees'),
    ],
    'indigenous': [
        ('Status cards & registration', 'Cartes de statut et inscription'),
        ('Band council matters', 'Affaires du conseil de bande'),
        ('Treaty rights', 'Droits issus des traites'),
        ('Reserve land issues', 'Questions foncieres des reserves'),
        ('Indigenous child welfare', 'Bien-etre des enfants autochtones'),
        ('Non-insured health benefits', 'Avantages de sante non assures'),
        ('Education on reserves', 'Education dans les reserves'),
        ('Missing and murdered Indigenous women', 'Femmes autochtones disparues ou assassinees'),
    ],
    'seniors': [
        ('Old Age Security (OAS)', 'Securite de la vieillesse (SV)'),
        ('Guaranteed Income Supplement (GIS)', 'Supplement de revenu garanti (SRG)'),
        ('Provincial senior supplements', 'Supplements provinciaux pour aines'),
        ('Long-term care complaints', 'Plaintes concernant les soins de longue duree'),
        ('Elder abuse', 'Maltraitance envers les aines'),
        ('Seniors\' property tax deferral', 'Report des impots fonciers pour aines'),
        ('Seniors\' drug benefits', 'Avantages pharmaceutiques pour aines'),
        ('Home care services', 'Services de soins a domicile'),
    ],
    'veterans': [
        ('Veterans\' disability benefits', 'Prestations d\'invalidite pour anciens combattants'),
        ('Veterans\' pension', 'Pension des anciens combattants'),
        ('Veterans Independence Program', 'Programme pour l\'autonomie des anciens combattants'),
        ('Veterans\' mental health services', 'Services de sante mentale pour anciens combattants'),
        ('Burial and grave marker maintenance', 'Enterrement et entretien des tombes'),
        ('Service records request', 'Demande de dossier de service'),
        ('Veteran ID card', 'Carte d\'identite d\'ancien combattant'),
    ],
    'disability': [
        ('Canada Pension Plan Disability', 'Pension d\'invalidite du RPC'),
        ('Canada Disability Benefit', 'Prestation canadienne pour personnes handicapees'),
        ('Provincial disability support', 'Soutien provincial pour personnes handicapees'),
        ('Disability Tax Credit', 'Credit d\'impot pour personnes handicapees'),
        ('Accessibility complaints', 'Plaintes en matiere d\'accessibilite'),
        ('Accessible parking permits', 'Permis de stationnement accessible'),
        ('Registered Disability Savings Plan', 'Regime d\'epargne-invalidite enregistre'),
    ],
    'youth': [
        ('Student loans', 'Prets etudiants'),
        ('Youth Employment Program', 'Programme d\'emploi pour les jeunes'),
        ('Canada Learning Bond', 'Bon d\'etudes canadien'),
        ('Apprenticeship grants', 'Subventions pour apprentis'),
        ('Youth mental health', 'Sante mentale des jeunes'),
        ('Youth justice', 'Justice pour les jeunes'),
        ('Student housing complaints', 'Plaintes concernant le logement etudiant'),
    ],
    'agriculture': [
        ('Farm income support', 'Soutien au revenu agricole'),
        ('Agricultural grants', 'Subventions agricoles'),
        ('Rural broadband', 'Internet a large bande rural'),
        ('Farm safety', 'Securite a la ferme'),
        ('Soil and water conservation', 'Conservation des sols et de l\'eau'),
        ('Agricultural land complaints', 'Plaintes concernant les terres agricoles'),
    ],
    'utilities': [
        ('Internet/cable complaints', 'Plaintes concernant Internet/le cable'),
        ('Electricity rates', 'Tarifs d\'electricite'),
        ('Natural gas rates', 'Tarifs du gaz naturel'),
        ('Water billing', 'Facturation de l\'eau'),
        ('Phone service complaints', 'Plaintes concernant le service telephonique'),
        ('Net metering/solar', 'Comptage net et solaire'),
    ],
    'family': [
        ('Marriage license', 'Permis de mariage'),
        ('Divorce', 'Divorce'),
        ('Child custody (unmarried parents)', 'Garde d\'enfants (parents non maries)'),
        ('Child support enforcement', 'Execution des pensions alimentaires pour enfants'),
        ('Spousal support', 'Pension alimentaire pour conjoint'),
        ('Property division', 'Partage des biens'),
        ('Adoption', 'Adoption'),
        ('Child protection', 'Protection de l\'enfance'),
    ],
    'arts': [
        ('Canada Council for the Arts grants', 'Subventions du Conseil des Arts du Canada'),
        ('Canadian Heritage funding', 'Financement de Patrimoine canadien'),
        ('Provincial arts council grants', 'Subventions des conseils des arts provinciaux'),
        ('Municipal cultural grants', 'Subventions culturelles municipales'),
        ('Film/TV tax credits', 'Credits d\'impot pour le cinema/television'),
        ('Heritage building designation', 'Designation des batiments patrimoniaux'),
    ],
    'lgbtq': [
        ('Gender identity & expression', 'Identite et expression de genre'),
        ('Conversion therapy', 'Therapie de conversion'),
        ('Legal name/gender change', 'Changement legal de nom/genre'),
        ('Healthcare access (trans healthcare)', 'Acces aux soins de sante (sante trans)'),
        ('Discrimination complaints', 'Plaintes pour discrimination'),
        ('2SLGBTQ+ youth support', 'Soutien aux jeunes 2SLGBTQ+'),
        ('Same-sex parent recognition', 'Reconnaissance des parents de meme sexe'),
        ('2SLGBTQ+ seniors\' care', 'Soins pour les aines 2SLGBTQ+'),
    ],
    'women': [
        ('Reproductive rights', 'Droits reproductifs'),
        ('Pay equity', 'Equite salariale'),
        ('Gender-based violence', 'Violence fondee sur le genre'),
        ('Women\'s shelters', 'Refuges pour femmes'),
        ('Maternity/parental leave', 'Conge de maternite/parental'),
        ('Childcare access', 'Acces aux services de garde'),
        ('Women in politics', 'Femmes en politique'),
        ('Sexual harassment at work', 'Harcèlement sexuel au travail'),
    ],
    'mentalhealth': [
        ('Mental health services', 'Services de sante mentale'),
        ('Crisis lines', 'Lignes de crise'),
        ('Therapy access', 'Acces a la therapie'),
        ('Workplace mental health', 'Sante mentale au travail'),
        ('Youth mental health', 'Sante mentale des jeunes'),
        ('Addiction treatment', 'Traitement des dependances'),
        ('Mental health in schools', 'Sante mentale a l\'ecole'),
        ('Involuntary treatment', 'Traitement involontaire'),
    ],
    'substance': [
        ('Addiction treatment centers', 'Centres de traitement des dependances'),
        ('Harm reduction (needle programs)', 'Reduction des mefaits (programmes d\'aiguilles)'),
        ('Safe supply', 'Approvisionnement securitaire'),
        ('Opioid crisis response', 'Reponse a la crise des opioides'),
        ('Recovery housing', 'Logements de retablissement'),
        ('Naloxone distribution', 'Distribution de naloxone'),
        ('Substance use in schools', 'Consommation de substances a l\'ecole'),
        ('Drug policy reform', 'Reforme de la politique des drogues'),
    ],
    'transportation': [
        ('Public transit funding', 'Financement du transport en commun'),
        ('Transit accessibility', 'Accessibilite du transport en commun'),
        ('Rural transportation', 'Transport rural'),
        ('Paratransit services', 'Services de paratransit'),
        ('Active transportation (bike lanes)', 'Transport actif (pistes cyclables)'),
        ('Transportation for seniors', 'Transport pour les aines'),
        ('School bus safety', 'Securite des autobus scolaires'),
        ('Ride-sharing regulations', 'Reglementation du covoiturage'),
    ],
    'digital': [
        ('Internet privacy', 'Confidentialite sur Internet'),
        ('Data breaches', 'Violations de donnees'),
        ('Net neutrality', 'Neutralite du reseau'),
        ('Digital ID', 'Identite numerique'),
        ('Cyberbullying', 'Cyberintimidation'),
        ('Online fraud', 'Fraude en ligne'),
        ('Social media harms', 'Mecontents des medias sociaux'),
        ('AI and automated decisions', 'IA et decisions automatisees'),
    ],
    'animals': [
        ('Animal cruelty', 'Cruaute envers les animaux'),
        ('Wildlife protection', 'Protection de la faune'),
        ('Pet regulations', 'Reglementation des animaux de compagnie'),
        ('Farm animal welfare', 'Bien-etre des animaux de ferme'),
        ('Exotic animal ownership', 'Possession d\'animaux exotiques'),
        ('Animal shelters', 'Refuges pour animaux'),
        ('Service animals', 'Animaux d\'assistance'),
    ],
    'sports': [
        ('Community sports programs', 'Programmes sportifs communautaires'),
        ('Recreation facilities', 'Installations recreatives'),
        ('Youth athletics', 'Athletisme pour les jeunes'),
        ('Safe sport', 'Sport securitaire'),
        ('Athlete funding', 'Financement des athletes'),
        ('Accessible recreation', 'Loisirs accessibles'),
        ('School sports', 'Sports scolaires'),
    ],
    'religion': [
        ('Religious freedom', 'Liberte religieuse'),
        ('Places of worship zoning', 'Zonage des lieux de culte'),
        ('Faith-based schools', 'Ecoles confessionnelles'),
        ('Religious accommodations at work', 'Accommodements religieux au travail'),
        ('Religious symbols', 'Symboles religieux'),
        ('Faith-based services', 'Services fondes sur la foi'),
        ('Interfaith relations', 'Relations interreligieuses'),
    ],
    'volunteer': [
        ('Volunteer opportunities', 'Possibilites de benevolat'),
        ('Community organizations', 'Organisations communautaires'),
        ('Civic engagement', 'Engagement civique'),
        ('Charity registration', 'Enregistrement des organismes de bienfaisance'),
        ('Volunteer liability', 'Responsabilite des benevoles'),
        ('Community grants', 'Subventions communautaires'),
        ('Nonprofit funding', 'Financement des organismes sans but lucratif'),
    ],
    'legalaid': [
        ('Legal aid eligibility', 'Admissibilite a l\'aide juridique'),
        ('Duty counsel', 'Avocat de service'),
        ('Family law legal aid', 'Aide juridique en matiere familiale'),
        ('Criminal legal aid', 'Aide juridique en matiere criminelle'),
        ('Immigration legal aid', 'Aide juridique en matiere d\'immigration'),
        ('Civil disputes', 'Differends civils'),
        ('Community legal clinics', 'Cliniques juridiques communautaires'),
        ('Access to justice', 'Acces a la justice'),
    ],
    'pensions': [
        ('Canada Pension Plan', 'Regime de pensions du Canada'),
        ('Workplace pensions', 'Regimes de pension professionnels'),
        ('Pension disputes', 'Differends relatifs aux pensions'),
        ('RRSPs and TFSAs', 'REER et CELI'),
        ('Retirement planning', 'Planification de la retraite'),
        ('Pension splitting divorce', 'Partage de pension lors du divorce'),
        ('Locked-in retirement accounts', 'Comptes de retraite bloques'),
        ('Senior financial abuse', 'Abus financier envers les aines'),
    ],
    'childcare': [
        ('Daycare access', 'Acces aux garderies'),
        ('Childcare subsidies', 'Subventions pour les services de garde'),
        ('Licensed childcare', 'Services de garde licences'),
        ('Unlicensed childcare', 'Services de garde non licences'),
        ('Before/after school care', 'Garde avant/apres l\'ecole'),
        ('Childcare worker wages', 'Salaires des travailleurs en garde d\'enfants'),
        ('Childcare complaints', 'Plaintes concernant les services de garde'),
        ('Early learning programs', 'Programmes d\'apprentissage precoce'),
    ],
    'food': [
        ('Food banks', 'Banques alimentaires'),
        ('School nutrition programs', 'Programmes de nutrition scolaire'),
        ('Food safety', 'Securite alimentaire'),
        ('Community gardens', 'Jardins communautaires'),
        ('Food deserts', 'Deserts alimentaires'),
        ('Northern food subsidies', 'Subventions alimentaires pour le Nord'),
        ('Food pricing', 'Prix des aliments'),
        ('Food charity regulations', 'Reglementation des organismes alimentaires'),
    ],
    'emergency': [
        ('911 services', 'Services 911'),
        ('Fire services', 'Services d\'incendie'),
        ('Paramedic services', 'Services paramedicaux'),
        ('Disaster response', 'Reponse aux catastrophes'),
        ('Emergency preparedness', 'Preparation aux urgences'),
        ('Search and rescue', 'Recherche et sauvetage'),
        ('Emergency alerts', 'Alertes d\'urgence'),
        ('Emergency shelter', 'Abris d\'urgence'),
    ],
    'humanrights': [
        ('Discrimination complaints', 'Plaintes pour discrimination'),
        ('Hate speech', 'Discours de haine'),
        ('Workplace discrimination', 'Discrimination au travail'),
        ('Housing discrimination', 'Discrimination en matiere de logement'),
        ('Accessibility rights', 'Droits a l\'accessibilite'),
        ('Language rights', 'Droits linguistiques'),
        ('Refugee rights', 'Droits des refugies'),
        ('International human rights', 'Droits de la personne internationaux'),
    ],
}

# Process each category
for cat_id, issues in translations.items():
    for eng, fr in issues:
        # Find and replace the issue name line
        pattern = rf'(\{{name:"' + re.escape(eng) + r'",)(primary:)'
        replacement = r'\g<1> nameFr:"' + fr + '",\g<2>'
        content = re.sub(pattern, replacement, content)

# Write back
with open(r'D:\source_extracted\index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('Done! Added nameFr fields to all issue names.')