// City Data for MyCivicVoice v4
// Canadian cities mapped to province + OpenNorth representative_set_name
// Generated: 2026-03-07
// Total cities: 472

const CITY_DATA = [
  { name: "Toronto", province: "ON", repSet: "Toronto City Council" },
  { name: "Ottawa", province: "ON", repSet: "Ottawa City Council" },
  { name: "Mississauga", province: "ON", repSet: "Mississauga City Council" },
  { name: "Brampton", province: "ON", repSet: "Brampton City Council" },
  { name: "Hamilton", province: "ON", repSet: "Hamilton City Council" },
  { name: "London", province: "ON", repSet: "London City Council" },
  { name: "Markham", province: "ON", repSet: "Markham City Council" },
  { name: "Vaughan", province: "ON", repSet: "Vaughan City Council" },
  { name: "Kitchener", province: "ON", repSet: "Kitchener City Council" },
  { name: "Windsor", province: "ON", repSet: "Windsor City Council" },
  { name: "Richmond Hill", province: "ON", repSet: "Richmond Hill Town Council" },
  { name: "Oakville", province: "ON", repSet: "Oakville Town Council" },
  { name: "Burlington", province: "ON", repSet: "Burlington City Council" },
  { name: "Oshawa", province: "ON", repSet: "Oshawa City Council" },
  { name: "Greater Sudbury", province: "ON", repSet: "Greater Sudbury City Council" },
  { name: "Guelph", province: "ON", repSet: "Guelph City Council" },
  { name: "Cambridge", province: "ON", repSet: "Cambridge City Council" },
  { name: "Whitby", province: "ON", repSet: "Whitby Town Council" },
  { name: "Kingston", province: "ON", repSet: "Kingston City Council" },
  { name: "Ajax", province: "ON", repSet: "Ajax Town Council" },
  { name: "Milton", province: "ON", repSet: "Milton Town Council" },
  { name: "Waterloo", province: "ON", repSet: "Waterloo City Council" },
  { name: "Thunder Bay", province: "ON", repSet: "Thunder Bay City Council" },
  { name: "Brantford", province: "ON", repSet: "Brantford City Council" },
  { name: "Niagara Falls", province: "ON", repSet: "Niagara Falls City Council" },
  { name: "Newmarket", province: "ON", repSet: "Newmarket Town Council" },
  { name: "Pickering", province: "ON", repSet: "Pickering City Council" },
  { name: "Peterborough", province: "ON", repSet: "Peterborough City Council" },
  { name: "Barrie", province: "ON", repSet: "Barrie City Council" },
  { name: "St. Catharines", province: "ON", repSet: "St. Catharines City Council" },
  { name: "Sarnia", province: "ON", repSet: "Sarnia City Council" },
  { name: "North Bay", province: "ON", repSet: "North Bay City Council" },
  { name: "Timmins", province: "ON", repSet: "Timmins City Council" },
  { name: "Orillia", province: "ON", repSet: "Orillia City Council" },
  { name: "Stratford", province: "ON", repSet: "Stratford City Council" },
  { name: "Belleville", province: "ON", repSet: "Belleville City Council" },
  { name: "Cornwall", province: "ON", repSet: "Cornwall City Council" },
  { name: "Quinte West", province: "ON", repSet: "Quinte West City Council" },
  { name: "Brockville", province: "ON", repSet: "Brockville City Council" },
  { name: "Pembroke", province: "ON", repSet: "Pembroke City Council" },
  { name: "Sault Ste. Marie", province: "ON", repSet: "Sault Ste. Marie City Council" },
  { name: "Elliot Lake", province: "ON", repSet: "Elliot Lake City Council" },
  { name: "Temiskaming Shores", province: "ON", repSet: "Temiskaming Shores City Council" },
  { name: "Kenora", province: "ON", repSet: "Kenora City Council" },
  { name: "Dryden", province: "ON", repSet: "Dryden City Council" },
  { name: "Fort Frances", province: "ON", repSet: "Fort Frances Town Council" },
  { name: "Sioux Lookout", province: "ON", repSet: "Sioux Lookout Town Council" },
  { name: "Moosonee", province: "ON", repSet: "Moosonee Town Council" },
  { name: "Cochrane", province: "ON", repSet: "Cochrane Town Council" },
  { name: "Hearst", province: "ON", repSet: "Hearst Town Council" },
  { name: "Kapuskasing", province: "ON", repSet: "Kapuskasing Town Council" },
  { name: "Kirkland Lake", province: "ON", repSet: "Kirkland Lake Town Council" },
  { name: "Parry Sound", province: "ON", repSet: "Parry Sound Town Council" },
  { name: "Huntsville", province: "ON", repSet: "Huntsville Town Council" },
  { name: "Bracebridge", province: "ON", repSet: "Bracebridge Town Council" },
  { name: "Gravenhurst", province: "ON", repSet: "Gravenhurst Town Council" },
  { name: "Midland", province: "ON", repSet: "Midland Town Council" },
  { name: "Penetanguishene", province: "ON", repSet: "Penetanguishene Town Council" },
  { name: "Collingwood", province: "ON", repSet: "Collingwood Town Council" },
  { name: "Wasaga Beach", province: "ON", repSet: "Wasaga Beach Town Council" },
  { name: "Innisfil", province: "ON", repSet: "Innisfil Town Council" },
  { name: "Bradford West Gwillimbury", province: "ON", repSet: "Bradford West Gwillimbury Town Council" },
  { name: "New Tecumseth", province: "ON", repSet: "New Tecumseth Town Council" },
  { name: "Kawartha Lakes", province: "ON", repSet: "Kawartha Lakes City Council" },
  { name: "Port Hope", province: "ON", repSet: "Port Hope Town Council" },
  { name: "Cobourg", province: "ON", repSet: "Cobourg Town Council" },
  { name: "Brighton", province: "ON", repSet: "Brighton Town Council" },
  { name: "Gananoque", province: "ON", repSet: "Gananoque Town Council" },
  { name: "Prescott", province: "ON", repSet: "Prescott Town Council" },
  { name: "Smiths Falls", province: "ON", repSet: "Smiths Falls Town Council" },
  { name: "Perth", province: "ON", repSet: "Perth Town Council" },
  { name: "Carleton Place", province: "ON", repSet: "Carleton Place Town Council" },
  { name: "Almonte", province: "ON", repSet: "Almonte Town Council" },
  { name: "Arnprior", province: "ON", repSet: "Arnprior Town Council" },
  { name: "Renfrew", province: "ON", repSet: "Renfrew Town Council" },
  { name: "Petawawa", province: "ON", repSet: "Petawawa Town Council" },
  { name: "Deep River", province: "ON", repSet: "Deep River Town Council" },
  { name: "Bancroft", province: "ON", repSet: "Bancroft Town Council" },
  { name: "Minden", province: "ON", repSet: "Minden Town Council" },
  { name: "Tweed", province: "ON", repSet: "Tweed Town Council" },
  { name: "Campbellford", province: "ON", repSet: "Campbellford Town Council" },
  { name: "Norwood", province: "ON", repSet: "Norwood Town Council" },
  { name: "Uxbridge", province: "ON", repSet: "Uxbridge Town Council" },
  { name: "Port Perry", province: "ON", repSet: "Port Perry Town Council" },
  { name: "Stouffville", province: "ON", repSet: "Stouffville Town Council" },
  { name: "Thornhill", province: "ON", repSet: "Thornhill Village Council" },
  { name: "Maple", province: "ON", repSet: "Maple Village Council" },
  { name: "Kleinburg", province: "ON", repSet: "Kleinburg Village Council" },
  { name: "Woodbridge", province: "ON", repSet: "Woodbridge Village Council" },
  { name: "Georgetown", province: "ON", repSet: "Georgetown Town Council" },
  { name: "Acton", province: "ON", repSet: "Acton Town Council" },
  { name: "Ancaster", province: "ON", repSet: "Ancaster Town Council" },
  { name: "Dundas", province: "ON", repSet: "Dundas Town Council" },
  { name: "Stoney Creek", province: "ON", repSet: "Stoney Creek Town Council" },
  { name: "Flamborough", province: "ON", repSet: "Flamborough Township Council" },
  { name: "Port Colborne", province: "ON", repSet: "Port Colborne City Council" },
  { name: "Welland", province: "ON", repSet: "Welland City Council" },
  { name: "Thorold", province: "ON", repSet: "Thorold City Council" },
  { name: "Niagara-on-the-Lake", province: "ON", repSet: "Niagara-on-the-Lake Town Council" },
  { name: "Fort Erie", province: "ON", repSet: "Fort Erie Town Council" },
  { name: "Grimsby", province: "ON", repSet: "Grimsby Town Council" },
  { name: "Lincoln", province: "ON", repSet: "Lincoln Town Council" },
  { name: "Pelham", province: "ON", repSet: "Pelham Town Council" },
  { name: "Wainfleet", province: "ON", repSet: "Wainfleet Township Council" },
  { name: "West Lincoln", province: "ON", repSet: "West Lincoln Township Council" },
  { name: "St. Thomas", province: "ON", repSet: "St. Thomas City Council" },
  { name: "Woodstock", province: "ON", repSet: "Woodstock City Council" },
  { name: "Ingersoll", province: "ON", repSet: "Ingersoll Town Council" },
  { name: "Tillsonburg", province: "ON", repSet: "Tillsonburg Town Council" },
  { name: "Norwich", province: "ON", repSet: "Norwich Township Council" },
  { name: "Bayham", province: "ON", repSet: "Bayham Township Council" },
  { name: "Central Elgin", province: "ON", repSet: "Central Elgin Township Council" },
  { name: "Dutton/Dunwich", province: "ON", repSet: "Dutton/Dunwich Township Council" },
  { name: "West Elgin", province: "ON", repSet: "West Elgin Township Council" },
  { name: "Montreal", province: "QC", repSet: "Montreal City Council" },
  { name: "Quebec City", province: "QC", repSet: "Quebec City Council" },
  { name: "Laval", province: "QC", repSet: "Laval City Council" },
  { name: "Gatineau", province: "QC", repSet: "Gatineau City Council" },
  { name: "Longueuil", province: "QC", repSet: "Longueuil City Council" },
  { name: "Sherbrooke", province: "QC", repSet: "Sherbrooke City Council" },
  { name: "Saguenay", province: "QC", repSet: "Saguenay City Council" },
  { name: "Levis", province: "QC", repSet: "Levis City Council" },
  { name: "Trois-Rivieres", province: "QC", repSet: "Trois-Rivieres City Council" },
  { name: "Terrebonne", province: "QC", repSet: "Terrebonne City Council" },
  { name: "Saint-Jean-sur-Richelieu", province: "QC", repSet: "Saint-Jean-sur-Richelieu City Council" },
  { name: "Granby", province: "QC", repSet: "Granby City Council" },
  { name: "Saint-Laurent", province: "QC", repSet: "Saint-Laurent Borough Council" },
  { name: "Lachine", province: "QC", repSet: "Lachine Borough Council" },
  { name: "Saint-Hyacinthe", province: "QC", repSet: "Saint-Hyacinthe City Council" },
  { name: "Blainville", province: "QC", repSet: "Blainville City Council" },
  { name: "Saint-Jerome", province: "QC", repSet: "Saint-Jerome City Council" },
  { name: "Drummondville", province: "QC", repSet: "Drummondville City Council" },
  { name: "Saint-Eustache", province: "QC", repSet: "Saint-Eustache City Council" },
  { name: "Rimouski", province: "QC", repSet: "Rimouski City Council" },
  { name: "Shawinigan", province: "QC", repSet: "Shawinigan City Council" },
  { name: "Rouyn-Noranda", province: "QC", repSet: "Rouyn-Noranda City Council" },
  { name: "Saint-Bruno-de-Montarville", province: "QC", repSet: "Saint-Bruno-de-Montarville City Council" },
  { name: "Saint-Constant", province: "QC", repSet: "Saint-Constant City Council" },
  { name: "Mont-Royal", province: "QC", repSet: "Mont-Royal Town Council" },
  { name: "Westmount", province: "QC", repSet: "Westmount City Council" },
  { name: "Dollard-des-Ormeaux", province: "QC", repSet: "Dollard-des-Ormeaux City Council" },
  { name: "Cote-Saint-Luc", province: "QC", repSet: "Cote-Saint-Luc City Council" },
  { name: "Pointe-Claire", province: "QC", repSet: "Pointe-Claire City Council" },
  { name: "Beaconsfield", province: "QC", repSet: "Beaconsfield City Council" },
  { name: "Kirkland", province: "QC", repSet: "Kirkland City Council" },
  { name: "Dorval", province: "QC", repSet: "Dorval City Council" },
  { name: "Sainte-Anne-de-Bellevue", province: "QC", repSet: "Sainte-Anne-de-Bellevue Town Council" },
  { name: "Senneville", province: "QC", repSet: "Senneville Village Council" },
  { name: "Baie-d'Urfe", province: "QC", repSet: "Baie-d'Urfe Town Council" },
  { name: "Sainte-Julie", province: "QC", repSet: "Sainte-Julie City Council" },
  { name: "Varennes", province: "QC", repSet: "Varennes City Council" },
  { name: "Repentigny", province: "QC", repSet: "Repentigny City Council" },
  { name: "Boucherville", province: "QC", repSet: "Boucherville City Council" },
  { name: "Beloeil", province: "QC", repSet: "Beloeil City Council" },
  { name: "Chambly", province: "QC", repSet: "Chambly City Council" },
  { name: "Saint-Basile-le-Grand", province: "QC", repSet: "Saint-Basile-le-Grand City Council" },
  { name: "Saint-Amable", province: "QC", repSet: "Saint-Amable City Council" },
  { name: "Vercheres", province: "QC", repSet: "Vercheres City Council" },
  { name: "Contrecoeur", province: "QC", repSet: "Contrecoeur City Council" },
  { name: "Sorel-Tracy", province: "QC", repSet: "Sorel-Tracy City Council" },
  { name: "Valleyfield", province: "QC", repSet: "Valleyfield City Council" },
  { name: "Saint-Lambert", province: "QC", repSet: "Saint-Lambert City Council" },
  { name: "Brossard", province: "QC", repSet: "Brossard City Council" },
  { name: "Chateauguay", province: "QC", repSet: "Chateauguay City Council" },
  { name: "La Prairie", province: "QC", repSet: "La Prairie City Council" },
  { name: "Candiac", province: "QC", repSet: "Candiac City Council" },
  { name: "Delson", province: "QC", repSet: "Delson City Council" },
  { name: "Saint-Philippe", province: "QC", repSet: "Saint-Philippe City Council" },
  { name: "Saint-Isidore", province: "QC", repSet: "Saint-Isidore City Council" },
  { name: "Saint-Mathieu", province: "QC", repSet: "Saint-Mathieu City Council" },
  { name: "Sainte-Catherine", province: "QC", repSet: "Sainte-Catherine City Council" },
  { name: "Saint-Remi", province: "QC", repSet: "Saint-Remi City Council" },
  { name: "Saint-Michel", province: "QC", repSet: "Saint-Michel City Council" },
  { name: "Mercier", province: "QC", repSet: "Mercier City Council" },
  { name: "Saint-Canut", province: "QC", repSet: "Saint-Canut City Council" },
  { name: "Saint-Janvier", province: "QC", repSet: "Saint-Janvier City Council" },
  { name: "Sainte-Therese", province: "QC", repSet: "Sainte-Therese City Council" },
  { name: "Rosemere", province: "QC", repSet: "Rosemere City Council" },
  { name: "Boisbriand", province: "QC", repSet: "Boisbriand City Council" },
  { name: "Sainte-Anne-des-Plaines", province: "QC", repSet: "Sainte-Anne-des-Plaines City Council" },
  { name: "Sainte-Sophie", province: "QC", repSet: "Sainte-Sophie City Council" },
  { name: "Saint-Hippolyte", province: "QC", repSet: "Saint-Hippolyte City Council" },
  { name: "Saint-Colomban", province: "QC", repSet: "Saint-Colomban City Council" },
  { name: "Mirabel", province: "QC", repSet: "Mirabel City Council" },
  { name: "Sainte-Marthe-sur-le-Lac", province: "QC", repSet: "Sainte-Marthe-sur-le-Lac City Council" },
  { name: "Saint-Joseph-du-Lac", province: "QC", repSet: "Saint-Joseph-du-Lac City Council" },
  { name: "Pointe-Calumet", province: "QC", repSet: "Pointe-Calumet City Council" },
  { name: "Saint-Placide", province: "QC", repSet: "Saint-Placide City Council" },
  { name: "Oka", province: "QC", repSet: "Oka City Council" },
  { name: "Hudson", province: "QC", repSet: "Hudson Town Council" },
  { name: "Rigaud", province: "QC", repSet: "Rigaud City Council" },
  { name: "Saint-Lazare", province: "QC", repSet: "Saint-Lazare City Council" },
  { name: "Vaudreuil-Dorion", province: "QC", repSet: "Vaudreuil-Dorion City Council" },
  { name: "Pincourt", province: "QC", repSet: "Pincourt Town Council" },
  { name: "Ile-Perrot", province: "QC", repSet: "Ile-Perrot Town Council" },
  { name: "Notre-Dame-de-l'Ile-Perrot", province: "QC", repSet: "Notre-Dame-de-l'Ile-Perrot Town Council" },
  { name: "Terrasse-Vaudreuil", province: "QC", repSet: "Terrasse-Vaudreuil Town Council" },
  { name: "Dorion", province: "QC", repSet: "Dorion Town Council" },
  { name: "Les Cedres", province: "QC", repSet: "Les Cedres Town Council" },
  { name: "Saint-Clet", province: "QC", repSet: "Saint-Clet Town Council" },
  { name: "Saint-Polycarpe", province: "QC", repSet: "Saint-Polycarpe Town Council" },
  { name: "Saint-Telephore", province: "QC", repSet: "Saint-Telephore Town Council" },
  { name: "Saint-Zotique", province: "QC", repSet: "Saint-Zotique Town Council" },
  { name: "Les Coteaux", province: "QC", repSet: "Les Coteaux Town Council" },
  { name: "Coteau-du-Lac", province: "QC", repSet: "Coteau-du-Lac Town Council" },
  { name: "Vancouver", province: "BC", repSet: "Vancouver City Council" },
  { name: "Victoria", province: "BC", repSet: "Victoria City Council" },
  { name: "Surrey", province: "BC", repSet: "Surrey City Council" },
  { name: "Burnaby", province: "BC", repSet: "Burnaby City Council" },
  { name: "Richmond", province: "BC", repSet: "Richmond City Council" },
  { name: "Kelowna", province: "BC", repSet: "Kelowna City Council" },
  { name: "Abbotsford", province: "BC", repSet: "Abbotsford City Council" },
  { name: "Coquitlam", province: "BC", repSet: "Coquitlam City Council" },
  { name: "Saanich", province: "BC", repSet: "Saanich District Council" },
  { name: "Langley", province: "BC", repSet: "Langley City Council" },
  { name: "Delta", province: "BC", repSet: "Delta City Council" },
  { name: "Nanaimo", province: "BC", repSet: "Nanaimo City Council" },
  { name: "Kamloops", province: "BC", repSet: "Kamloops City Council" },
  { name: "Prince George", province: "BC", repSet: "Prince George City Council" },
  { name: "New Westminster", province: "BC", repSet: "New Westminster City Council" },
  { name: "North Vancouver", province: "BC", repSet: "North Vancouver City Council" },
  { name: "West Vancouver", province: "BC", repSet: "West Vancouver City Council" },
  { name: "Port Coquitlam", province: "BC", repSet: "Port Coquitlam City Council" },
  { name: "Port Moody", province: "BC", repSet: "Port Moody City Council" },
  { name: "Maple Ridge", province: "BC", repSet: "Maple Ridge City Council" },
  { name: "Mission", province: "BC", repSet: "Mission District Council" },
  { name: "Chilliwack", province: "BC", repSet: "Chilliwack City Council" },
  { name: "Langford", province: "BC", repSet: "Langford City Council" },
  { name: "Oak Bay", province: "BC", repSet: "Oak Bay District Council" },
  { name: "Esquimalt", province: "BC", repSet: "Esquimalt Town Council" },
  { name: "Colwood", province: "BC", repSet: "Colwood City Council" },
  { name: "View Royal", province: "BC", repSet: "View Royal Town Council" },
  { name: "Highlands", province: "BC", repSet: "Highlands District Council" },
  { name: "Metchosin", province: "BC", repSet: "Metchosin District Council" },
  { name: "Sooke", province: "BC", repSet: "Sooke District Council" },
  { name: "Central Saanich", province: "BC", repSet: "Central Saanich District Council" },
  { name: "North Saanich", province: "BC", repSet: "North Saanich District Council" },
  { name: "Sidney", province: "BC", repSet: "Sidney Town Council" },
  { name: "Juan de Fuca", province: "BC", repSet: "Juan de Fuca District Council" },
  { name: "Salt Spring Island", province: "BC", repSet: "Salt Spring Island Local Trust Council" },
  { name: "Penticton", province: "BC", repSet: "Penticton City Council" },
  { name: "Vernon", province: "BC", repSet: "Vernon City Council" },
  { name: "Courtenay", province: "BC", repSet: "Courtenay City Council" },
  { name: "Campbell River", province: "BC", repSet: "Campbell River City Council" },
  { name: "Powell River", province: "BC", repSet: "Powell River City Council" },
  { name: "Sunshine Coast", province: "BC", repSet: "Sunshine Coast Regional District" },
  { name: "Squamish", province: "BC", repSet: "Squamish District Council" },
  { name: "Whistler", province: "BC", repSet: "Whistler Resort Municipality Council" },
  { name: "Pemberton", province: "BC", repSet: "Pemberton Village Council" },
  { name: "Hope", province: "BC", repSet: "Hope District Council" },
  { name: "Agassiz", province: "BC", repSet: "Agassiz District Council" },
  { name: "Harrison Hot Springs", province: "BC", repSet: "Harrison Hot Springs Village Council" },
  { name: "Sechelt", province: "BC", repSet: "Sechelt District Council" },
  { name: "Gibsons", province: "BC", repSet: "Gibsons Town Council" },
  { name: "Comox", province: "BC", repSet: "Comox Town Council" },
  { name: "Cumberland", province: "BC", repSet: "Cumberland Village Council" },
  { name: "Qualicum Beach", province: "BC", repSet: "Qualicum Beach Town Council" },
  { name: "Parksville", province: "BC", repSet: "Parksville City Council" },
  { name: "Ladysmith", province: "BC", repSet: "Ladysmith Town Council" },
  { name: "Lake Cowichan", province: "BC", repSet: "Lake Cowichan Town Council" },
  { name: "Duncan", province: "BC", repSet: "Duncan City Council" },
  { name: "North Cowichan", province: "BC", repSet: "North Cowichan District Council" },
  { name: "Cowichan Bay", province: "BC", repSet: "Cowichan Bay Town Council" },
  { name: "Shawnigan Lake", province: "BC", repSet: "Shawnigan Lake District Council" },
  { name: "Mill Bay", province: "BC", repSet: "Mill Bay Town Council" },
  { name: "Malahat", province: "BC", repSet: "Malahat District Council" },
  { name: "Brentwood Bay", province: "BC", repSet: "Brentwood Bay Town Council" },
  { name: "Calgary", province: "AB", repSet: "Calgary City Council" },
  { name: "Edmonton", province: "AB", repSet: "Edmonton City Council" },
  { name: "Red Deer", province: "AB", repSet: "Red Deer City Council" },
  { name: "Lethbridge", province: "AB", repSet: "Lethbridge City Council" },
  { name: "Medicine Hat", province: "AB", repSet: "Medicine Hat City Council" },
  { name: "St. Albert", province: "AB", repSet: "St. Albert City Council" },
  { name: "Grande Prairie", province: "AB", repSet: "Grande Prairie City Council" },
  { name: "Airdrie", province: "AB", repSet: "Airdrie City Council" },
  { name: "Fort McMurray", province: "AB", repSet: "Fort McMurray City Council" },
  { name: "Spruce Grove", province: "AB", repSet: "Spruce Grove City Council" },
  { name: "Leduc", province: "AB", repSet: "Leduc City Council" },
  { name: "Lloydminster", province: "AB", repSet: "Lloydminster City Council" },
  { name: "Camrose", province: "AB", repSet: "Camrose City Council" },
  { name: "Chestermere", province: "AB", repSet: "Chestermere City Council" },
  { name: "Cold Lake", province: "AB", repSet: "Cold Lake City Council" },
  { name: "Fort Saskatchewan", province: "AB", repSet: "Fort Saskatchewan City Council" },
  { name: "Beaumont", province: "AB", repSet: "Beaumont Town Council" },
  { name: "Okotoks", province: "AB", repSet: "Okotoks Town Council" },
  { name: "Canmore", province: "AB", repSet: "Canmore Town Council" },
  { name: "Banff", province: "AB", repSet: "Banff Town Council" },
  { name: "Strathmore", province: "AB", repSet: "Strathmore Town Council" },
  { name: "High River", province: "AB", repSet: "High River Town Council" },
  { name: "Nanton", province: "AB", repSet: "Nanton Town Council" },
  { name: "Vulcan", province: "AB", repSet: "Vulcan Town Council" },
  { name: "Taber", province: "AB", repSet: "Taber Town Council" },
  { name: "Vauxhall", province: "AB", repSet: "Vauxhall Town Council" },
  { name: "Bow Island", province: "AB", repSet: "Bow Island Town Council" },
  { name: "Claresholm", province: "AB", repSet: "Claresholm Town Council" },
  { name: "Fort Macleod", province: "AB", repSet: "Fort Macleod Town Council" },
  { name: "Pincher Creek", province: "AB", repSet: "Pincher Creek Town Council" },
  { name: "Crowsnest Pass", province: "AB", repSet: "Crowsnest Pass District Council" },
  { name: "Blairmore", province: "AB", repSet: "Blairmore Town Council" },
  { name: "Coleman", province: "AB", repSet: "Coleman Town Council" },
  { name: "Bellevue", province: "AB", repSet: "Bellevue Town Council" },
  { name: "Hillcrest", province: "AB", repSet: "Hillcrest Town Council" },
  { name: "Frank", province: "AB", repSet: "Frank Town Council" },
  { name: "Lundbreck", province: "AB", repSet: "Lundbreck Town Council" },
  { name: "Cowley", province: "AB", repSet: "Cowley Town Council" },
  { name: "Waterton Park", province: "AB", repSet: "Waterton Park Town Council" },
  { name: "Cardston", province: "AB", repSet: "Cardston Town Council" },
  { name: "Magrath", province: "AB", repSet: "Magrath Town Council" },
  { name: "Raymond", province: "AB", repSet: "Raymond Town Council" },
  { name: "Stirling", province: "AB", repSet: "Stirling Town Council" },
  { name: "Milk River", province: "AB", repSet: "Milk River Town Council" },
  { name: "Coutts", province: "AB", repSet: "Coutts Village Council" },
  { name: "Warner", province: "AB", repSet: "Warner Town Council" },
  { name: "Lethbridge County", province: "AB", repSet: "Lethbridge County Council" },
  { name: "Newell County", province: "AB", repSet: "Newell County Council" },
  { name: "Saskatoon", province: "SK", repSet: "Saskatoon City Council" },
  { name: "Regina", province: "SK", repSet: "Regina City Council" },
  { name: "Prince Albert", province: "SK", repSet: "Prince Albert City Council" },
  { name: "Moose Jaw", province: "SK", repSet: "Moose Jaw City Council" },
  { name: "Yorkton", province: "SK", repSet: "Yorkton City Council" },
  { name: "Swift Current", province: "SK", repSet: "Swift Current City Council" },
  { name: "North Battleford", province: "SK", repSet: "North Battleford City Council" },
  { name: "Estevan", province: "SK", repSet: "Estevan City Council" },
  { name: "Weyburn", province: "SK", repSet: "Weyburn City Council" },
  { name: "Martensville", province: "SK", repSet: "Martensville City Council" },
  { name: "Warman", province: "SK", repSet: "Warman City Council" },
  { name: "Humboldt", province: "SK", repSet: "Humboldt City Council" },
  { name: "Meadow Lake", province: "SK", repSet: "Meadow Lake City Council" },
  { name: "Nipawin", province: "SK", repSet: "Nipawin Town Council" },
  { name: "Kindersley", province: "SK", repSet: "Kindersley Town Council" },
  { name: "Melville", province: "SK", repSet: "Melville City Council" },
  { name: "Melfort", province: "SK", repSet: "Melfort City Council" },
  { name: "Battlefords", province: "SK", repSet: "Battlefords City Council" },
  { name: "La Ronge", province: "SK", repSet: "La Ronge Town Council" },
  { name: "Creighton", province: "SK", repSet: "Creighton Town Council" },
  { name: "Flin Flon", province: "SK", repSet: "Flin Flon City Council" },
  { name: "Uranium City", province: "SK", repSet: "Uranium City Town Council" },
  { name: "Cumberland House", province: "SK", repSet: "Cumberland House Town Council" },
  { name: "Stony Rapids", province: "SK", repSet: "Stony Rapids Town Council" },
  { name: "Black Lake", province: "SK", repSet: "Black Lake Town Council" },
  { name: "Wollaston Lake", province: "SK", repSet: "Wollaston Lake Town Council" },
  { name: "Buffalo Narrows", province: "SK", repSet: "Buffalo Narrows Town Council" },
  { name: "Ile-a-la-Crosse", province: "SK", repSet: "Ile-a-la-Crosse Town Council" },
  { name: "Green Lake", province: "SK", repSet: "Green Lake Town Council" },
  { name: "Beauval", province: "SK", repSet: "Beauval Town Council" },
  { name: "La Loche", province: "SK", repSet: "La Loche Town Council" },
  { name: "Patuanak", province: "SK", repSet: "Patuanak Town Council" },
  { name: "Dillon", province: "SK", repSet: "Dillon Town Council" },
  { name: "Michel Village", province: "SK", repSet: "Michel Village Town Council" },
  { name: "Winnipeg", province: "MB", repSet: "Winnipeg City Council" },
  { name: "Brandon", province: "MB", repSet: "Brandon City Council" },
  { name: "Steinbach", province: "MB", repSet: "Steinbach City Council" },
  { name: "Thompson", province: "MB", repSet: "Thompson City Council" },
  { name: "Portage la Prairie", province: "MB", repSet: "Portage la Prairie City Council" },
  { name: "Selkirk", province: "MB", repSet: "Selkirk City Council" },
  { name: "Winkler", province: "MB", repSet: "Winkler City Council" },
  { name: "Dauphin", province: "MB", repSet: "Dauphin City Council" },
  { name: "Morden", province: "MB", repSet: "Morden City Council" },
  { name: "The Pas", province: "MB", repSet: "The Pas Town Council" },
  { name: "Grand Rapids", province: "MB", repSet: "Grand Rapids Town Council" },
  { name: "Norway House", province: "MB", repSet: "Norway House Town Council" },
  { name: "Oxford House", province: "MB", repSet: "Oxford House Town Council" },
  { name: "Cross Lake", province: "MB", repSet: "Cross Lake Town Council" },
  { name: "Nelson House", province: "MB", repSet: "Nelson House Town Council" },
  { name: "York Factory", province: "MB", repSet: "York Factory Town Council" },
  { name: "Churchill", province: "MB", repSet: "Churchill Town Council" },
  { name: "Gillam", province: "MB", repSet: "Gillam Town Council" },
  { name: "Leaf Rapids", province: "MB", repSet: "Leaf Rapids Town Council" },
  { name: "Lynn Lake", province: "MB", repSet: "Lynn Lake Town Council" },
  { name: "Snow Lake", province: "MB", repSet: "Snow Lake Town Council" },
  { name: "Shamattawa", province: "MB", repSet: "Shamattawa Town Council" },
  { name: "Tadoule Lake", province: "MB", repSet: "Tadoule Lake Town Council" },
  { name: "Brochet", province: "MB", repSet: "Brochet Town Council" },
  { name: "Lac Brochet", province: "MB", repSet: "Lac Brochet Town Council" },
  { name: "St. Theresa Point", province: "MB", repSet: "St. Theresa Point Town Council" },
  { name: "Garden Hill", province: "MB", repSet: "Garden Hill Town Council" },
  { name: "Wasagamack", province: "MB", repSet: "Wasagamack Town Council" },
  { name: "Moncton", province: "NB", repSet: "Moncton City Council" },
  { name: "Saint John", province: "NB", repSet: "Saint John City Council" },
  { name: "Fredericton", province: "NB", repSet: "Fredericton City Council" },
  { name: "Dieppe", province: "NB", repSet: "Dieppe City Council" },
  { name: "Riverview", province: "NB", repSet: "Riverview Town Council" },
  { name: "Bathurst", province: "NB", repSet: "Bathurst City Council" },
  { name: "Edmundston", province: "NB", repSet: "Edmundston City Council" },
  { name: "Miramichi", province: "NB", repSet: "Miramichi City Council" },
  { name: "Campbellton", province: "NB", repSet: "Campbellton City Council" },
  { name: "Quispamsis", province: "NB", repSet: "Quispamsis Town Council" },
  { name: "Rothesay", province: "NB", repSet: "Rothesay Town Council" },
  { name: "Grand Falls", province: "NB", repSet: "Grand Falls Town Council" },
  { name: "Oromocto", province: "NB", repSet: "Oromocto Town Council" },
  { name: "Shediac", province: "NB", repSet: "Shediac Town Council" },
  { name: "Sackville", province: "NB", repSet: "Sackville Town Council" },
  { name: "Hampton", province: "NB", repSet: "Hampton Town Council" },
  { name: "Sussex", province: "NB", repSet: "Sussex Town Council" },
  { name: "St. Andrews", province: "NB", repSet: "St. Andrews Town Council" },
  { name: "Dalhousie", province: "NB", repSet: "Dalhousie Town Council" },
  { name: "Bouctouche", province: "NB", repSet: "Bouctouche Town Council" },
  { name: "Richibucto", province: "NB", repSet: "Richibucto Town Council" },
  { name: "Tracadie", province: "NB", repSet: "Tracadie Town Council" },
  { name: "Shippagan", province: "NB", repSet: "Shippagan Town Council" },
  { name: "Neguac", province: "NB", repSet: "Neguac Town Council" },
  { name: "Halifax", province: "NS", repSet: "Halifax Regional Council" },
  { name: "Cape Breton", province: "NS", repSet: "Cape Breton Regional Council" },
  { name: "Sydney", province: "NS", repSet: "Sydney Town Council" },
  { name: "Truro", province: "NS", repSet: "Truro Town Council" },
  { name: "New Glasgow", province: "NS", repSet: "New Glasgow Town Council" },
  { name: "Kentville", province: "NS", repSet: "Kentville Town Council" },
  { name: "Amherst", province: "NS", repSet: "Amherst Town Council" },
  { name: "Bridgewater", province: "NS", repSet: "Bridgewater Town Council" },
  { name: "Yarmouth", province: "NS", repSet: "Yarmouth Town Council" },
  { name: "Antigonish", province: "NS", repSet: "Antigonish Town Council" },
  { name: "Wolfville", province: "NS", repSet: "Wolfville Town Council" },
  { name: "Port Hawkesbury", province: "NS", repSet: "Port Hawkesbury Town Council" },
  { name: "Lunenburg", province: "NS", repSet: "Lunenburg Town Council" },
  { name: "Digby", province: "NS", repSet: "Digby Town Council" },
  { name: "Shelburne", province: "NS", repSet: "Shelburne Town Council" },
  { name: "Liverpool", province: "NS", repSet: "Liverpool Town Council" },
  { name: "Pictou", province: "NS", repSet: "Pictou Town Council" },
  { name: "Springhill", province: "NS", repSet: "Springhill Town Council" },
  { name: "Oxford", province: "NS", repSet: "Oxford Town Council" },
  { name: "Parrsboro", province: "NS", repSet: "Parrsboro Town Council" },
  { name: "Guysborough", province: "NS", repSet: "Guysborough Town Council" },
  { name: "Canso", province: "NS", repSet: "Canso Town Council" },
  { name: "Baddeck", province: "NS", repSet: "Baddeck Town Council" },
  { name: "Ingonish", province: "NS", repSet: "Ingonish Town Council" },
  { name: "Charlottetown", province: "PE", repSet: "Charlottetown City Council" },
  { name: "Summerside", province: "PE", repSet: "Summerside City Council" },
  { name: "Montague", province: "PE", repSet: "Montague Town Council" },
  { name: "Kensington", province: "PE", repSet: "Kensington Town Council" },
  { name: "Souris", province: "PE", repSet: "Souris Town Council" },
  { name: "Alberton", province: "PE", repSet: "Alberton Town Council" },
  { name: "O'Leary", province: "PE", repSet: "O'Leary Town Council" },
  { name: "Tignish", province: "PE", repSet: "Tignish Town Council" },
  { name: "Tyne Valley", province: "PE", repSet: "Tyne Valley Town Council" },
  { name: "Miminegash", province: "PE", repSet: "Miminegash Town Council" },
  { name: "Ellerslie", province: "PE", repSet: "Ellerslie Town Council" },
  { name: "Borden-Carleton", province: "PE", repSet: "Borden-Carleton Town Council" },
  { name: "St. John's", province: "NL", repSet: "St. John's City Council" },
  { name: "Mount Pearl", province: "NL", repSet: "Mount Pearl City Council" },
  { name: "Corner Brook", province: "NL", repSet: "Corner Brook City Council" },
  { name: "Conception Bay South", province: "NL", repSet: "Conception Bay South Town Council" },
  { name: "Paradise", province: "NL", repSet: "Paradise Town Council" },
  { name: "Gander", province: "NL", repSet: "Gander Town Council" },
  { name: "Grand Falls-Windsor", province: "NL", repSet: "Grand Falls-Windsor Town Council" },
  { name: "Clarenville", province: "NL", repSet: "Clarenville Town Council" },
  { name: "Carbonear", province: "NL", repSet: "Carbonear Town Council" },
  { name: "Bay Roberts", province: "NL", repSet: "Bay Roberts Town Council" },
  { name: "Marystown", province: "NL", repSet: "Marystown Town Council" },
  { name: "Happy Valley-Goose Bay", province: "NL", repSet: "Happy Valley-Goose Bay Town Council" },
  { name: "Labrador City", province: "NL", repSet: "Labrador City Town Council" },
  { name: "Churchill Falls", province: "NL", repSet: "Churchill Falls Town Council" },
  { name: "Wabush", province: "NL", repSet: "Wabush Town Council" },
  { name: "Port aux Basques", province: "NL", repSet: "Port aux Basques Town Council" },
  { name: "Stephenville", province: "NL", repSet: "Stephenville Town Council" },
  { name: "Deer Lake", province: "NL", repSet: "Deer Lake Town Council" },
  { name: "Springdale", province: "NL", repSet: "Springdale Town Council" },
  { name: "Lewisporte", province: "NL", repSet: "Lewisporte Town Council" },
  { name: "Whitehorse", province: "YT", repSet: "Whitehorse City Council" },
  { name: "Dawson City", province: "YT", repSet: "Dawson City Town Council" },
  { name: "Watson Lake", province: "YT", repSet: "Watson Lake Town Council" },
  { name: "Haines Junction", province: "YT", repSet: "Haines Junction Village Council" },
  { name: "Mayo", province: "YT", repSet: "Mayo Village Council" },
  { name: "Yellowknife", province: "NT", repSet: "Yellowknife City Council" },
  { name: "Hay River", province: "NT", repSet: "Hay River Town Council" },
  { name: "Fort Smith", province: "NT", repSet: "Fort Smith Town Council" },
  { name: "Inuvik", province: "NT", repSet: "Inuvik Town Council" },
  { name: "Norman Wells", province: "NT", repSet: "Norman Wells Town Council" },
  { name: "Iqaluit", province: "NU", repSet: "Iqaluit City Council" },
  { name: "Rankin Inlet", province: "NU", repSet: "Rankin Inlet Town Council" },
  { name: "Arviat", province: "NU", repSet: "Arviat Town Council" },
  { name: "Baker Lake", province: "NU", repSet: "Baker Lake Town Council" },
  { name: "Cambridge Bay", province: "NU", repSet: "Cambridge Bay Town Council" },
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CITY_DATA };
}
